### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by valerino** [mark-hahn/tab-smart-sort#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [tab-smart-sort](https://github.com/mark-hahn/tab-smart-sort) package, v0.1.2
### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
  at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11:15)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:374:25)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:326:20)
  at Pane.addItem (/Users/valerino/.atom/packages/tab-smart-sort/lib/tab-smart-sort.coffee:60:19)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:297:14)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:159:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -2:50.3.0 core:paste (atom-text-editor.editor.is-focused)
     -2:49.4.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -2:49.1.0 core:move-up (atom-text-editor.editor.is-focused)
 14x -2:48.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:23.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:19.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:19 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:18.7.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:18.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -2:17.9.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -2:16.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:16 core:backspace (atom-text-editor.editor.is-focused)
     -2:15.4.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:14.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:14.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:32.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "tab-smart-sort": {
    "ordering": "base, ext, dir"
  }
}
```
### Installed Packages

``` coffee
# User
atom-terminal-panel, v4.4.4
docblockr, v0.7.1
file-icons, v1.5.5
hex, v0.6.2
linter, v0.12.2
linter-cpplint, v0.1.4
symbols-tree-view, v0.9.2
synced-sidebar, v0.2.3
tab-smart-sort, v0.1.2
text-manipulation, v0.6.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
Thanks.  Fixed in 0.1.3

**Comment by baxeico** [comment]
[Enter steps to reproduce below:]
1. open new pane
2. drag a tab from a pane to another

**Atom Version**: 1.1.0
**System**: Ubuntu 12.04.5
**Thrown From**: [tab-smart-sort](https://github.com/mark-hahn/tab-smart-sort) package, v0.1.4

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /usr/share/atom/resources/app.asar/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
  at ItemRegistry.module.exports.ItemRegistry.addItem (/usr/share/atom/resources/app.asar/src/item-registry.js:11:15)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:374:25)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:359:28
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:339:20)
  at Pane.addItem (/home/augusto/.atom/packages/tab-smart-sort/lib/tab-smart-sort.coffee:67:19)
  at Pane.module.exports.Pane.moveItemToPane (/usr/share/atom/resources/app.asar/src/pane.js:424:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:706:20)
  at TabBarView.module.exports.TabBarView.onDrop (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:632:23)
  at space-pen-ul.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -1:26.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:26.1.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -1:26.1.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -1:25.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:53.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:52.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:52.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:52.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:52 core:paste (atom-text-editor.editor.is-focused)
     -0:51.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -0:51.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:49.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
  9x -0:48.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:47.2.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:46.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:44.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  },
  "tab-smart-sort": {}
}
```

### Installed Packages

``` coffee
# User
atom-django, v0.3.0
django-templates, v0.5.0
highlight-selected, v0.10.1
minimap, v4.16.0
minimap-highlight-selected, v4.3.1
pretty-json, v0.4.1
tab-smart-sort, v0.1.4

# Dev
No dev packages
```

**Comment by bedge** [comment]
[Enter steps to reproduce below:]

```
Make a copy of a pane with Cmd <right arrow>
drag that tab to another pane
```

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [tab-smart-sort](https://github.com/mark-hahn/tab-smart-sort) package, v0.1.4

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:374:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:359:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:355:20)
    at Pane.addItem (/Users/bedge/.atom/packages/tab-smart-sort/lib/tab-smart-sort.coffee:122:28)
    at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:440:19)
    at atom-tabs.TabBarView.moveItemBetweenPanes (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:729:20)
    at atom-tabs.TabBarView.onDrop (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:615:23)
```

### Commands

```
     -4:37.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -4:35.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -4:32.1.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -4:09.7.0 quick-highlight:toggle (atom-text-editor.editor.is-focused)
     -4:05.2.0 pane:split-right (atom-text-editor.editor.is-focused)
  3x -2:52.5.0 core:close (atom-text-editor.editor.is-focused)
     -1:48.7.0 quick-highlight:toggle (atom-text-editor.editor.is-focused)
     -1:46.7.0 pane:split-right (atom-text-editor.editor.is-focused)
     -1:44.5.0 quick-highlight:clear (atom-text-editor.editor.is-focused)
     -1:18 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "wrap-guide",
      "atom-ctags",
      "file-header",
      "git-time-machine",
      "git-grep",
      "tree-view-git-modified"
    ],
    "packagesWithKeymapsDisabled": [
      "select-rectangle"
    ],
    "projectHome": "/Users/bedge/git",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "tab-smart-sort": {
    "ordering": "base, ext, dir",
    "placeSpecialTabsOnRight": true
  }
}
```

### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-beautify, v0.28.26
atom-html-preview, v0.1.17
atom-yamljson, v0.2.3
color-picker, v2.1.1
color-tabs, v0.1.8
colorful-json, v1.0.0
compare-files, v0.6.2
docblockr, v0.7.3
file-types, v0.5.1
git-diff-details, v0.23.0
git-log, v0.4.1
highlight-column, v0.5.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
json-schema, v0.1.15
jsonlint, v1.1.2
language-crontab, v0.2.1
language-gradle, v0.0.3
language-groovy, v0.5.0
language-tmux, v0.4.0
last-cursor-position, v0.9.0
linter, v1.11.3
linter-javac, v1.8.1
linter-js-yaml, v1.2.5
linter-jsonlint, v1.1.6
linter-package-json-validator, v1.0.1
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
linter-shellcheck, v1.1.0
local-history, v3.2.3
markdown-mindmap, v0.2.4
minimap, v4.20.0
minimap-bookmarks, v0.3.0
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
minimap-selection, v4.4.0
multi-wrap-guide, v0.23.5
multirow-tabs, v0.3.3
open-recent, v5.0.0
package-sync, v1.0.0
pigments, v0.24.5
pretty-json, v0.4.1
quick-highlight, v0.3.10
select-rectangle, v1.0.2
tab-control, v0.6.9
tab-smart-sort, v0.1.4
tab-switcher, v1.3.3
tab-title, v0.3.3
tabs-to-spaces, v1.0.2
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by alimoosavi15** [comment]
I'm still having this issue in 0.1.4

``````
/opt/atom/resources/app.asar/src/item-registry.js:11
Hide Stack Trace
Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/opt/atom/resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/opt/atom/resources/app.asar/src/pane-container.js:387:25)
    at /opt/atom/resources/app.asar/src/pane-container.js:372:28
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (/opt/atom/resources/app.asar/src/pane.js:485:20)
    at Pane.addItem (/home/alimoosavi15/.atom/packages/tab-smart-sort/lib/tab-smart-sort.coffee:122:28)
    at Pane.module.exports.Pane.moveItemToPane (/opt/atom/resources/app.asar/src/pane.js:610:19)
    at atom-tabs.TabBarView.moveItemBetweenPanes (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:726:20)
    at atom-tabs.TabBarView.onDrop (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:603:23)```
``````
